AllCops:
  TargetRubyVersion: 2.6.6

LineLength:
  Max: 140

Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Naming/MethodParameterName:
  MinNameLength: 1

Metrics/MethodLength:
  Max: 20